package com.ssafy.sosangomin.common.exception;

import lombok.Getter;

@Getter
public enum ErrorMessage {

    /**
     * 400 Bad Request
     */
    ERR_INVALID_REQUEST_FIELD,
    ERR_INVALID_QUERY_PARAMETER,
    ERR_INVALID_MAIL_NUMBER,
    ERR_NAME_DUPLICATE,
    ERR_EMAIL_DUPLICATE,
    ERR_LOGIN_FAILED,
    ERR_USER_DUPLICATE,
    ERR_ANALYZE_BAD_REQUEST,
    ERR_INVALID_SOURCE_ID,
    ERR_INVALID_ANALYSIS_FORMAT,
    ERR_INVALID_CHAT_REQUEST,
    ERR_INVALID_STORE_ID,
    ERR_INVALID_COMPARISON_ID,
    ERR_MY_STORE_ANALYSIS_NOT_FOUND,
    ERR_INVALID_REVIEW_REQUEST,
    ERR_INVALID_ANALYSIS_ID,
    ERR_INVALID_USER_ID,
    ERR_INVALID_STORE_NAME,
    ERR_INVALID_BUSINESS_NUMBER,
    ERR_BUSINESS_NUMBER_VERIFICATION_FAILED,
    ERR_INVALID_AREA_REQUEST,
    ERR_INVALID_REGION_NAME,
    ERR_INVALID_REPORT_ID,

    /**
     * 401 UNAUTHORIZED
     */
    ERR_INVALID_TOKEN,
    ERR_USER_BOARD_NOT_MATCH,
    ERR_USER_COMMENT_NOT_MATCH,
    ERR_NOT_ALLOWD_USER,
    ERR_USER_STORE_NOT_MATCH,

    /**
     * /** 404 NOT_FOUND
     */
    ERR_NOT_RESOURCE,
    ERR_USER_NOT_FOUND,
    ERR_BOARD_NOT_FOUND,
    ERR_COMMENT_NOT_FOUND,
    ERR_NOTICE_NOT_FOUND,
    ERR_ANALYSIS_RESULT_NOT_FOUND,
    ERR_LATEST_RESULT_NOT_FOUND,
    ERR_CHATBOT_SERVICE_NOT_FOUND,
    ERR_COMPETITOR_COMPARISON_NOT_FOUND,
    ERR_COMPARISON_RESULT_NOT_FOUND,
    ERR_REVIEW_ANALYSIS_NOT_FOUND,
    ERR_DATASOURCE_NOT_FOUND,
    ERR_STORE_NOT_FOUND,
    ERR_COMPETITOR_NOT_FOUND,
    ERR_REPORT_NOT_FOUND,

    /**
     * 500 INTERNAL_SERVER_ERROR
     */
    ERR_INTERNAL_SERVER_ENCRYPTION_ERROR,
    ERR_INTERNAL_SERVER_DECRYPTION_ERROR,
    ERR_INTERNAL_SERVER_MAIL_SEND_FAIL_ERROR,
    ERR_INTERNAL_SERVER_PROFILE_IMG_UPLOAD_FAIL_ERROR,
    ERR_ANALYSIS_PROCESSING_ERROR,
    ERR_CHAT_PROCESSING_ERROR,
    ERR_COMPETITOR_COMPARISON_PROCESSING_ERROR,
    ERR_COMPETITOR_ANALYSIS_PROCESSING_ERROR,
    ERR_COMPARISON_RESULT_PROCESSING_ERROR,
    ERR_REVIEW_ANALYSIS_PROCESSING_ERROR,
    ERR_REVIEW_LIST_PROCESSING_ERROR,
    ERR_REVIEW_RESULT_PROCESSING_ERROR,
    ERR_ANALYSIS_RESULTS_LIST_ERROR,
    ERR_DATASOURCE_LIST_PROCESSING_ERROR,
    ERR_DATASOURCE_PROCESSING_ERROR,
    ERR_STORE_REGISTRATION_ERROR,
    ERR_STORE_LIST_PROCESSING_ERROR,
    ERR_STORE_DETAIL_PROCESSING_ERROR,
    ERR_INTERNAL_SERVER_COMMUNICATION,
    ERR_AREA_ANALYSIS_PROCESSING_ERROR,
    ERR_POPULATION_ANALYSIS_PROCESSING_ERROR,
    ERR_STORE_ANALYSIS_PROCESSING_ERROR,
    ERR_SALES_ANALYSIS_PROCESSING_ERROR,
    ERR_INTERNAL_SERVER_ERROR,
    ERR_REPORT_LIST_PROCESSING_ERROR,
    ERR_REPORT_PROCESSING_ERROR,
    ERR_REPORT_GENERATION_ERROR,
    ERR_SET_MAIN_STORE_ERROR,
    ERR_STORE_DELETE_ERROR
}
